== Im Fehlerfall

Ist die Eingabe fehlerhaft oder treten sonstige Fehler bei der Verarbeitung des Services auf,
wird an den Client ein *Internal Server Error*, bzw. *Server Code 500*, gesendet.

Auf dem *Server* wird in der Tabelle xtcasError ein Eintrag mit dem Username, dem genauen Zeitpunkt und dem aufgetretenen Fehler erstellt.
[source,sql]
----
insert into xtcasError (Username, ErrorMessage, Date) values (username,errorMessage,date)
----


Das Rückgabeformat der Tabelle, welche an den *Client* gesendet wird, kann folgende Formate besitzen:

 1. Sql-Fehler-Format1
 2. Programm-Fehler-Format
 3. Sql-Fehler-Format2

=== Sql-Fehler-Format1

.Ursprünglich Fehlermeldung
[source]
----
ADO | 25 | msg.Error @p tTable.Description.7 @p tTable.Description.14 | Default Message
----

Das Sql-Fehler Format wird dann auftreten, wenn es einen Fehler in einer oder mehreren Prozeduren gibt.

Das CAS wird diesen in folgender Form ausgeben:


.Sql-Fehler-Format1
[source,json]
----
{
    "resultSet": {
        "name": "Error",
        "columns": [
            {
                "name": "International Message",
                "type": "STRING"
            },
            {
                "name": "p",
                "type": "STRING"
            },
            {
                "name": "p",
                "type": "STRING"
            },
            {
                "name": "DEFAULT",
                "type": "STRING"
            }
        ],
        "rows": [
            {
                "values": [
                    "s-msg.Error",
                    "s-tTable.Description.7",
                    "s-tTable.Description.14",
                    "s-Default Message"
                ]
            }
        ],
	"returnErrorMessage": {
		"detailsMessage": "ExceptionMessage",
		"cause": "ExceptionCause",
		"trace": [
			"StackTraceMessages",
			...
		]
	},
    "returnCodes": [
        -1
    ],
    "returnCode": -1
}
----


Es wird immer im ersten Value die Kurzform der Fehlermeldung 'msg.*' stehen.
In der letzten Spalte namens 'DEFAULT' steht immer die Standard-Übersetzung der Fehlermeldung.

Die Columns zwischen 'International Message' und 'DEFAULT' sind Parameter, welche in der Original-Fehlermeldung mit '@[Datentyp]' gekennzeichnet waren.
Folgende Datentypen existieren:

* d = Datum in Schreibweise TTMMJJJJ
* d.iso = Datum in ISO Schreibweise JJJJMMTT
* f = Dezimalzahl
* f.iso = Dezimalzahl im ISO Format ( # . # # #)
* s = String
* p = Property aus den Properties. Wird dann genau so nachgeschlagen, wie Properties in Java-Programmen.
* i = Integer

Als Value wird in der Row der String-Value eingefügt, 
welcher nach dem @[Datentyp]-Parameter in der Original-Fehlermeldung steht.


.Beipiel
[source]
----
@p tTable.Description.7
----
wird zu 
[source,json]
----
...
"columns:" [
...
,{
                "name": "p",
                "type": "STRING"
            },
...
"rows": [
            {
                "values": [
                    ...
                    "s-tTable.Description.7",
                    ...
                ]
            }
        ],
----

=== Programm-Fehler-Format
.Programm-Fehler-Format
[source,json]
----
{
	"name": "Error",
    "columns": [
        {
            "name": "International Message",
            "type": "STRING"
        }
        [,{
        	"name": "MessageInputParam1",
            "type": "STRING"
            }]
    ],
    "rows": [
        {
            "values": [
                "s-msg.Error",["s-InputParameter",...]
            ]
        }
    ],
	"returnErrorMessage": {
		"detailsMessage": "ExceptionMessage",
		"cause": "ExceptionCause",
		"trace": [
			"StackTraceMessages",
			...
		]
	}
----
Der Name der zurückgegebenen Tabele wird auf "Error" geändert und es wird nur eine Row zurückgegeben,
in welcher der übersetzbare MessageCode hinterlegt ist, welcher beim Client in die Sprache des Users übersetzt wird.

Falls die Nachricht einen oder mehrere Inputparameter benötigt, folgen weitere String-Values, welche die einzelnen Parameter enthalten.

Die returnErrorMessage beinhaltet immer eine detailsMessage, einen cause und einen trace.

Sie wird nur befüllt, falls ein Fehler auftritt.
Ansonsten ist dieses Objekt *null*.


=== Sql-Fehler-Format2

.Ursprünglich Fehlermeldung
[source]
----
ADO | 30 | delaycode.description.comma | Commas are not allowed in the description.
----

Das Sql-Fehler Format wird dann auftreten, wenn es einen Fehler in einer oder mehreren Prozeduren gibt.

Das CAS wird diesen in folgender Form ausgeben:


.Sql-Fehler-Format2
[source,json]
----
{
    "resultSet": {
        "name": "Error",
        "columns": [
            {
                "name": "International Message",
                "type": "STRING"
            },
            {
                "name": "DEFAULT",
                "type": "STRING"
            }
        ],
        "rows": [
            {
                "values": [
                    "s-delaycode.description.comma",
                    "s-Commas are not allowed in the description."
                ]
            }
        ],
	"returnErrorMessage": {
		"detailsMessage": "ExceptionMessage",
		"cause": "ExceptionCause",
		"trace": [
			"StackTraceMessages",
			...
		]
	},
    "returnCodes": [
        -1
    ],
    "returnCode": -1
}
----

Die beiden Sql-Fehler-Formate sind sich sehr ähnlich. 
Der wesentliche Unterschied zwischen den beiden ist, dass die *International Message* kein 'msg.' am Anfang hat.
Die Verarbeitung der '@[Datentyp]'-Parameter bleibt aber gleich.

Dementsprechend ist der Ablauf und die Rückgabe der Werte derselbe wie bei Sql-Fehler-Format1.

==== returnErrorMessage/detailsMessage

Die DetailsMessage der Exception, die geworfen wurde.

==== returnErrorMessage/cause

Der Grund, weshalb die Exception geworfen wurde, z.b.:
_java.lang.NullPointerException_.

==== returnErrorMessage/trace

=== Sql-Fehler-Format3

.Ursprünglich Fehlermeldung
[source]
----
ADO | 30 | msg.sql.1234
----

Das Sql-Fehler Format wird dann auftreten, wenn es einen Fehler in einer oder mehreren Prozeduren gibt.

Das CAS wird diesen in folgender Form ausgeben:


.Sql-Fehler-Format2
[source,json]
----
{
    "resultSet": {
        "name": "Error",
        "columns": [
            {
                "name": "International Message",
                "type": "STRING"
            },
            {
                "name": "DEFAULT",
                "type": "STRING"
            }
        ],
        "rows": [
            {
                "values": [
                    "s-msg.sql.1234",
                    "s-msg.sql.1234"
                ]
            }
        ],
	"returnErrorMessage": {
		"detailsMessage": "ExceptionMessage",
		"cause": "ExceptionCause",
		"trace": [
			"StackTraceMessages",
			...
		]
	},
    "returnCodes": [
        -1
    ],
    "returnCode": -1
}
----

In diesem Fall ist kein Default gegeben. 
Deshalb wird die message selbst auch als Default ans WFC geliefert.
Der Ablauf und die Rückgabe der Werte derselbe wie bei Sql-Fehler-Format1.

==== returnErrorMessage/detailsMessage

Die DetailsMessage der Exception, die geworfen wurde.

==== returnErrorMessage/cause

Der Grund, weshalb die Exception geworfen wurde, z.b.:
_java.lang.NullPointerException_.

==== returnErrorMessage/trace

Der StackTrace der geworfenen Exception nach jedem Abatz getrennt.
