FROM alpine-java:base
MAINTAINER baeldung.com
COPY target/aero.minova.cas.jar /opt/aero.minova.cas/lib/
ENV SPRING_APPLICATION_JSON='{}'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/aero.minova.cas/lib/aero.minova.cas.jar"]
VOLUME /var/lib/aero.minova.cas
EXPOSE 8888