== Vergeben von Berechtigungen für AD-Gruppen

Damit der User über seine AD-Gruppen Privilegien erhalten und nutzen kann,
müssen folgende Schritte befolgt werden:

=== 1. application.properties

Die *login_dataSource* des CAS muss in den application.properties auf *'ldap'* gesetzt werden.

=== 2. Eintrag in xtcasUserGroup

Die AD-Gruppe muss in der Datenbank in die xtcasUserGroup eingetragen werden.

Hierbei muss die Schreibweise des Gruppennamens ganz genau beibehalten werden.
Die SecurityToken dürfen jedoch abweichen bzw. auch komplett anders heißen.

.Beispiel: Die AD-Gruppe heißt 'BeiSPielGrupPpE'.
[source,sql]
----
-- AD-Gruppenname = BeiSPielGrupPpE

insert into xtcasUserGroup (KeyText,SecurityToken) values ('BeiSPielGrupPpE','#adgruppe')
----

=== 3. Privilegien der Gruppe zuweisen

Da nun die AD-Gruppe mit der xtcasUserGroup in der Datenbank verbunden ist,
können über die xtcasLuUserPrivilegesUserGroup die Privilegien an die Gruppe verknüpft werden.

.Beispiel: Die Gruppe 'BeiSPielGrupPpE' darf die View 'vBeispiel' und die Prozedur 'pBeispiel' aufrufen.
[source,sql]
----
-- AD-Gruppenname = BeiSPielGrupPpE
declare @UserGroupKey int,
		@UserPrivilegeKey int
		
select @UserGroupKey = KeyLong from xtcasUserGroup where KeyText = 'BeiSPielGrupPpE'

select @UserPrivilegeKey = KeyLong from xtcasUserPrivilege where KeyText = 'BeispielProzedurOderView'

insert into xtcasLuUserPrivilegeUserGroup (UserGroupKey, UserPrivilegeKey, LastDate, LastUser, LastAction, RowLevelSecurity) values ( @UserGroupKey, @UserPrivilegeKey, getDate(), 'support', 1, 1)

----
