= Extensions bzw. Erweiterungen und App-Projekte

Es gibt keine Unterscheidung von Extensions und App-Projekten.
Diese werden jetzt über einen Projekt-Typ umgesetzt.

Es muss nur ein spezielles Parent in der POM verwendet werden.
Als Parent hat man die Wahl zwischen 2 verschiedenen POMs:

* `cas.extension.parent` wird verwendet, wenn die Erweiterung nur als Abhängigkeit verwendet wird.
    Also beispielsweise für eine Erweiterung, welche eine Lieferscheinmaske bereitstellt.
* `cas.extension.deployment` wird verwendet, wenn die Erweiterung ausgeliefert wird und nicht als Abhängigkeit verwendet wird.
    Also beispielsweise für Kundenprojekte die installiert werden.

Der Hintergrund für die 2 verschiedenen Parents ist,
dass zur Zeit, Erweiterungen nicht gleichzeit als Hauptprojekt ausgeliefert und
selber wiederum als Abhängigkeit verwendet werden können.
Der Grund dafür wiederum ist, dass `cas.extension.deployment` die Datei `aero.minova.app.resources/deployed.resources.txt` in die Jar einfügt,
welche nur einmalig vorhanden sein sollte.
Mit der `cas.extension.parent` wird verhindert,
dass es die `aero.minova.app.resources/deployed.resources.txt` mehrmals gibt.

Zudem sollte die Property `fat.jar.mode` auf `true` und `aero_minova_core_application_root_path` muss auf `/` gesetzt werden.

Beispielhafte application.properties:

```
server.port=8082

# Benötigt für CAS 13 
fat.jar.mode=true
aero_minova_core_application_root_path=/

server.servlet.context-path=/cas

# Login-Art: admin, database oder ldap
login_dataSource=admin

# Datenbankverbindung
spring.datasource.url=jdbc:postgresql://localhost:5432/saraco #Beispiel Postgres
# spring.datasource.url=jdbc:sqlserver://localhost;databaseName=sam;encrypt=false #Beispiel SQL
spring.datasource.username=XXX
spring.datasource.password=XXX
```

TODO: Vielleicht könnten wird die Aufteilung in `cas.extension.parent` und `cas.extension.deployment` in Zukunft irgendwie abschaffen.


Alle internen und externen Abhängigkeiten können frei hinzugefügt werden.

Minimale POM:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>cas-customer-build-project</artifactId>
    <version>13.0.0-SNAPSHOT</version>
    <parent>
        <groupId>aero.minova</groupId>
        <artifactId>cas.extension.deployment</artifactId>
        <version>13.0.6</version>
        <relativePath></relativePath>
    </parent>
    <scm>
        <connection>scm:git:https://github.com/minova-afis/[TODO].git</connection>
    </scm>
</project>
```

== Extensions mit Spring Application

Wenn man das CAS nicht über `aero.minova.cas.CoreApplicationSystemApplication` startet,
sondern eine eigene Klasse mit Spring-Boot verwendet,
sollten folgende Annotationen verwendet werden:

```
package aero.minova.example;

import java.util.TimeZone;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@ComponentScan({ "aero.minova", "com.minova" })
@EntityScan({ "aero.minova", "com.minova" })
@Configuration
public class ExampleApplication {
	public static void main(String[] args) {
		TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
		SpringApplication.run(ExampleApplication.class, args);
	}
}
```

== Erweiterungs-Registierung

Hierzu muss bei dem jeweiligen Controller nur die Methode *'registerExtension'* aufgerufen werden.
Hierbei muss darauf geachtet werden, dass keine zwei Extensions mit demselben Namen exisiteren.
In diesem Fall wird eine entsprechenede Exception geworfen.

Alle registierten Erweiterungen werden beim 'Setup' automatisch als Recht mit installiert und können so einfacher an die Rollen vergeben werden.
Denn bevor eine Extension ausgeführt wird, werden die Rollen des Nutzers, der die Anfrage stellt, erst einmal darauf überprüft,
ob das entsprechende Recht für die Extension vorhanden ist.

1. Controller-Klasse im src/main/java des extension-Projektes erstellen und dort je nach Bedarf den SQLViewController, den XSqlProcedureController und/oder den SqlProcedureController eintragen. Hier das @Autowired nicht vergessen.

2. Eine Setup-Methode erstellen, welche mit der @PostConstruct-Annotation gekennziechet ist. Diese muss die *'registerExtension'*-Methode des vorher importierten Controllers aufrufen und damit die Extension mit dem dazugehörigen Keyword registrieren.

3. Wenn in einer Extension etwas geloggt werden muss, wird dies über den CustomLogger gemacht. Welche Methode des Loggers für welchen Fall verwendet werden müssen, wird xref:./logs.adoc#[hier] erklärt.

Die Klasse sollte am Ende ungefähr so aussehen:
----
import org.springframework.web.bind.annotation.RestController;

import aero.minova.cas.CustomLogger;
import aero.minova.cas.controller.SqlProcedureController;
import aero.minova.cas.controller.SqlViewController;

@RestController
public class ExampleController {

	@Autowired
	SqlProcedureController sqlProcedureController;

	@Autowired
	XSqlProcedureController xsqlProcedureController;

	@Autowired
	SqlViewController sqlViewController;

	@Autowired
	CustomLogger customLogger;

	@PostConstruct
	public void setup() {
		// fügt Extension hinzu
		sqlProcedureController.registerExtension("xpcasBeispiel", this::doSomething);
	}

	private ResponseEntity<SqlProcedureResult> doSomething(Table inputTable) {
		customLogger.logUserRequest("Hier wird etwas gemacht!");
		return ResponseEntity//
				.ok()//
				.contentType(MediaType.APPLICATION_JSON)//
				.body(new SqlProcedureResult());
	}
----

== Besonderheiten

* Die Extensions sind selbst dafür verwantwortlich, im Fehlerfall Rollbacks durchzuführen.
* Gibt eine Extension null zurück, so wird die Prozedur/Transaktion zusätzlich als SQL ausgeführt
