= Extensions bzw. Erweiterungen und App-Projekte

Es gibt keine Unterscheidung von Extensions und App-Projekten.
Diese werden jetzt über einen Projekt-Typ umgesetzt.

Es muss nur eine spezielles Parent in der POM verwendet werden.
Abhängigkeiten können frei hinzugefügt werden,
wobei mindestens `aero.minova.cas.app` als Abhängigkeit angeben werden muss.
Es dürfen keine weiteren Plugins etc. verwendet werden.

Für Kundenprojekt die ausgeliefert werden,
muss in dem Projekt-Verzeichnis die Datei `this-is-deployed-project.txt` vorhanden sein.
Ist dies nicht der Fall, wird das so gebaute CAS nicht vollständig funktionieren.
Der Inhalt ist egal, da dies nur als Trigger für Maven verwendet wird.
Kundenprojekte mit `this-is-deployed-project.txt` dürfen nicht als Abhängigkeit verwendet werden.

 TODO: Vielleicht eine zusätzliche Parent statt `this-is-deployed-project.txt` verwenden?

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>cas-customer-build-project</artifactId>
    <version>12.67.1-SNAPSHOT</version>
    <description>Stellt sicher, dass im CAS image nur das verfügbar ist,
        was im CAS-App auch veröffentlicht wurde und nicht Dinge,
        welche durch dessen POM reinkopiert wurde.
        Folglich darf diese POM keine Plugins enthalten.
    </description>
    <parent>
        <groupId>aero.minova</groupId>
        <artifactId>cas.extension.parent</artifactId>
        <version>12.67.1-SNAPSHOT</version>
        <relativePath>../cas.extension.parent</relativePath>
    </parent>
    <dependencies>
        <dependency>
            <groupId>aero.minova</groupId>
            <artifactId>cas.app</artifactId>
            <version>12.67.1-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <scm>
        <connection>scm:git:https://github.com/minova-afis/aero.minova.cas.git</connection>
        <tag>v12.64.0</tag>
    </scm>
</project>
```