= Extensions bzw. Erweiterungen

Es können beim CAS Erweiterungen, sowohl für Prozeduren, als auch für Views registiert werden.
Wenn eine Prozedur oder View aufgerufen wird,
wird im CAS geprüft, ob es eine passende Erweiterung dazu gibt.
Ist dies der Fall wird diese aufgerufen, anstatt den SQL-Server zu befragen.

Es reicht in der Regel nicht, wenn die Erweiterung im Klassenpfad ist,
da diese beim Prozedur oder View-Aufruf sonst nicht aktiv sind.

== Zweck von Erweiterungen

Erweiterungen erlauben es zusätzliche Funktionalitäten zum CAS hinzuzufügen.
Erweiterungen sind nicht dazu da, sämtliche Funktionalitäten des Gesamtsystems in den CAS-Dienst einzubauen.
Folgendes sind legitime Einsatzzwecke:

* SQL mit JPA-Code ersetzen, wobei große Funktionalitäten, wie die Bestandsaufnahme (`aero.minova.stock.service`),
  in eigene Dienste gesteckt werden sollen.
* Nachrichten an andere Dienste schicken, wenn bestimmte Anfragen an das CAS kommen.
* Ein vorläufiger Ersatz um kleine Jobs und Ähnliches umsetzen.

== Aufbau von Erweiterungen

Alle Abhängigkeiten von Erweiterungen müssen den scope provided haben.
Diese Abhängigkeiten stehen somit während des Bauens zur Verfügung,
werden aber beim Deployment durch das CAS bereitgestellt.
Als Abhängigkeit sind für Erweiterungen nur das CAS und andere CAS-Erweiterungen erlaubt.

Erweiterungen dürfen keine eigene Abhängigkeit mitbringen,
da dies zu Versionen-Konflikten führen wird
(dieselbe Jar ist in den Lib-Ordner des CAS-Dienstes in unterschiedlichen Version mehrmals vorhanden).

Somit stellt das CAS alle Abhängigkeiten wie JPA und ähnliches zur Verfügung.
Fehlt eine Abhängigkeit, muss diese in den CAS-Dienst selber mit eingebaut werden.
Allerdings, ist es eine Einzelfall-Entscheidung,
ob diese zusätzliche Abhängigkeit übernommen wird oder nicht.
Damit wird verhindert, dass das CAS nicht unnötig aufgebläht wird.

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
    <groupId>aero.minova</groupId>
    <artifactId>cas.job.email</artifactId>
    <version>12.4.9-SNAPSHOT</version>
    <parent>
        <groupId>aero.minova</groupId>
        <artifactId>spring.maven.root</artifactId>
        <version>1.3.3</version>
        <relativePath/>
    </parent>
	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
	</properties>
	<dependencies>
		<dependency>
			<groupId>aero.minova</groupId>
			<artifactId>cas.setup</artifactId>
			<version>12.45.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>aero.minova</groupId>
			<artifactId>cas.service</artifactId>
			<version>12.45.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<scm>
		<connection>scm:git:https://github.com/minova-afis/aero.minova.cas.job.email</connection>
		<developerConnection>scm:git:https://github.com/minova-afis/aero.minova.cas.job.email</developerConnection>
		<tag>v12.3.0</tag>
	</scm>
</project>
```

== Erweiterungs-Registierung

Hierzu muss bei dem jeweiligen Controller nur die Methode *'registerExtension'* aufgerufen werden. 
Hierbei muss darauf geachtet werden, dass keine zwei Extensions mit demselben Namen exisiteren. 
In diesem Fall wird eine entsprechenede Exception geworfen.

Alle registierten Erweiterungen werden beim 'Setup' automatisch als Recht mit installiert und können so einfacher an die Rollen vergeben werden.
Denn bevor eine Extension ausgeführt wird, werden die Rollen des Nutzers, der die Anfrage stellt, erst einmal darauf überprüft,
ob das entsprechende Recht für die Extension vorhanden ist.

== Standard-Prozedur-Erweiterungen
* xpcasEncodePassword: nimmt eine Tabelle mit den Spalten `password` und `encodedPassword` entgegen.
Die Passwörter in der Spalte `password` werden kodiert und das Ergebnis in `encodedPassword` abgelegt.
Die so gehashten Passwörter können in `xtcasUsers.Password` verwendet werden.