# CAS für die Entwicklungsumgebung aufsetzen.

Es wird Java 11 und Maven benötigt.

## In Eclipse ausführen und debuggen.

In Eclipse:

* Repository runterladen: `git clone git@github.com:minova-afis/aero.minova.cas.git`
* Repo als Maven-Projekt in Eclipse importieren.
* Gesamtes Projekt bauen: `mvn clean install`
** Im `Package Explorer` das Projekt `cas.root` aufklappen.
** `pom.xml` Rechts klicken und `Run As` -> `Maven build...` auswählen.
** `clean install` in den Goals eintragen und `Run` klicken.
* Die `Java Application`-`Run Configuration` erstellen:
** Unter Main als `Project` `cas.dev` auswählen.
** Unter Main als `Main Class` `aero.minova.cas.CoreApplicationSystemApplication` eintragen.
** Unter Arguments in `Working Directory` `Others:` selektieren und mit `File System...` einen Ausführungs-Ordner für das CAS auswählen.
   Dieser muss unter Umständen erstellt werden und enthält Dateien (wie bspw. Konfigurationen) für das lokale CAS.

CAS-Ordner einrichten:

* CAS-Ordner erstellen (der selbe wie in der `Run Configuration)`.
* In `<Testsystem-Ordner>` die Datei `application.properties` anlegen und mit passenden Werten füllen.
Folgendes ist eine häufig nützliche minimal Konfiguration:
[source,properties]
```
login_dataSource=admin
aero_minova_database_url=<jdbc:sqlserver://host.docker.internal;encrypt=false;databaseName=test>
aero_minova_database_user_name=<Datenbank-Nutzer>
aero_minova_database_user_password=<Passwort>
logging_level_root=DEBUG
aero_minova_core_application_root_path=<Testsystem-Ordner>/system-files
```
* `<Testsystem-Ordner>/system-files` erstellen und mit Masken etc. füllen.
Falls man nicht weiss, wass man reintun soll:
man kann aus dem CAS-Repo den Inhalt des Ordners `app/target/docker-layer` in den `<Testsystem-Ordner>/system-files` kopieren.

Jetzt kann man das CAS mit der erstellen `Run Configuration` in Eclipse starten.

## Snapshot-Docker-Image lokal bauen und ausführen.

* Repository runterladen: `git clone git@github.com:minova-afis/aero.minova.cas.git`
* Shell in lokalen Repo öffnen: `cd <Pfad zum Repo-Ordner>/aero.minova.cas`
* Projekt bauen: `mvn clean verify`
* Docker-Image bauen: `docker build --tag=localtest .`
* Docker-Image starten:
[source,shell]
----
docker run \
    --name=localtest \
    --publish=8084:8084 \
    --env login_dataSource='admin' \
    --env aero_minova_database_url='jdbc:sqlserver://host.docker.internal;encrypt=false;databaseName=test' \
    --env aero_minova_database_user_name='Nutzer' \
    --env aero_minova_database_user_password='Passwort' \
    --env logging_level_root=DEBUG \
    localtest
----
* Alle Rechte können den admin-Nutzer übergeben werden, wenn folgendes auf SQL-Datenbank ausgeführt wird: `exec xpcasInsertAllPrivilegesToUserGroup 'admin', 'admin'`
* Docker-Image wieder entfernen: `docker rmi -f localtest`

## Snapshot-Docker-Image lokal bauen, ausführen und Masken live editieren.

Wenn man gerade an einer Maske arbeitet,
kann es Sinn machen, dass man eine Änderung testen kann, ohne dabei alles neu zu bauen und zu starten.

Dazu geht man in das Maskenprojekt und baut dieses einmal via `mvn clean verify`.
Danach starten man das Maskenprojekt als Docker-Container (Dockerfile wird benötigt) und
bindet dabei den `target/docker-layer` des App-Projekts ein.

Wenn man dann die Maske editiert hat,
muss man diese im passenden `<Benutzer-Ordner>/.minwfc/*/*.xml`-Ordner löschen.
In der WFC-Anwendung muss man die Maske nur noch schließen und wieder öffnen,
um diese zu aktualisieren.

Der Docker-Befehl ist unter Windows leichter anders als unter Unix-ähnlichen Systemen.

### Unix-ähnlichen

[source,shell]
----
docker rmi -f dev_cas3
docker build --tag=dev_cas2 .
docker rmi -f dev_cas3
docker build --tag=dev_cas2 .
docker run \
    --name=dev_cas3 \
    --publish=8084:8084 \
    --env login_dataSource='admin' \
    --env aero_minova_database_url='jdbc:sqlserver://host.docker.internal;encrypt=false;databaseName=test' \
    --env aero_minova_database_user_name='Nutzer' \
    --env aero_minova_database_user_password='Passwort' \
    --env logging_level_root=DEBUG \
    --env aero_minova_core_application_root_path='/opt/aero.minova.cas/system-files-override/' \
    -v "$(pwd)/target/docker-layer/:/opt/aero.minova.cas/system-files-override/" \
    dev_cas2
----

### Windows

Eine Ausführung in der Git Bash funktioniert nicht wie erhofft.
Stattdessen kann man die PowerShell verwenden:

[source,powershell]
----
docker rmi -f dev_cas3
docker build --tag=dev_cas2 .
docker rmi -f dev_cas3
docker build --tag=dev_cas2 .
docker run --name=dev_cas3 `
        --publish=8084:8084 `
        --env login_dataSource='admin' `
        --env aero_minova_database_url='jdbc:sqlserver://host.docker.internal;encrypt=false;databaseName=AFIS_GDN' `
        --env aero_minova_database_user_name='sa' `
        --env aero_minova_database_user_password='Minova+0' `
        --env logging_level_root=DEBUG `
        --env app_log_root='./target/logs' `
        --env aero_minova_core_application_root_path='/opt/aero.minova.cas/system-files-override/' `
        -v ${pwd}\target\docker-layer\:/opt/aero.minova.cas/system-files-override/ `
        dev_cas2
----
=======
