== Postgre-Datenbank

Wird eine Postgre-Datenbank verwendet,
kann die Setup Extension des CAS *nicht* verwendet werden.

Die für Postgre angepassten Skripte zur Installation der sicherheitrelevanten Tabellen, Views und Prozeduren befinden sich in 
*app/app/postgresql*.

Diese müssen dann von Hand auf der Datenbank ausgeführt werden.

Da Postgresql RowCount als Funktion verwendet, wird eine andere Methode zum Zusammenbauen des preparedStatements verwendet und zwar die prepareViewString-Methode.

=== Properties

Die application.properties müssen desweiteren mit folgenden Properties geändert werden:

* spring.jooq.sql-dialect=POSTGRESQL
* spring.datasource.url=jdbc:postgresql://URLZurDatenbank/DatenbankName
* spring.datasource.username=UsernameVonPostgresDatenbank
* spring.datasource.password=PasswortDesBenutzersDerPostgresDatenbank

JOOQ ist selbst in der Lage den richtigen Dialekt zum Interpretieren der Query zu ermitteln.

Falls dies aus unerfindlichen Gründen doch nicht geschieht, muss folgende Property hinzugefügt werden:

*spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect*