= Properties des Dienstes

Hier werden die Properties gelistet, die durch diesen Dienst definiert werden.

IMPORTANT: Falls eine Property in den application.properties verändert wird, *muss* das CAS neugestartet werden!

== Links

* Zurück zur xref:index.adoc[Übersicht]


== Richtlinien

1. Wird eine neue Property, die das CAS betrifft, erstellt, sollte diese mit *cas.* beginnen.
2. Handelt es sich dabei um eine Property für eine Extension, sollte danach der Name der Extension folgen. 
Heißt das Projekt der Extension zum Beispiel 'aero.minova.example', sollte die Property *'cas.example. ...'* genannt werden.
3. Die Trennzeichen zwischen den Worten sind *Punkte*. Siehe 'files.permission.check'.


== Standard Properties

* server.port
** *Default*: `8084`

* management.server.port
** *Default*: `8081`
** *Beschreibung*: Setzt den Port unter dem die Endpunkte des SpringBoot Actuators zu finden sind.

* management.endpoints.web.exposure.include
** *Default*: `*`
** *Beschreibung*: Siehe https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html

== JPA Properties

* spring.jpa.hibernate.ddl-auto
** *Default*: `none`
** *Wertebereich*: none , validate , update , create-drop
** *Beschreibung*: link:https://docs.spring.io/spring-boot/docs/1.1.0.M1/reference/html/howto-database-initialization.html[Spring-Doku]

* spring.jpa.defer-datasource-initialization
** *Default*: `false`
** *Wertebereich*: true, false
** *Beschreibung*: Wenn true, werden erst die JPA Tabellen aufgespielt, bevor Queries aus data.sql ausgeführt werden. Wenn die JPA Tabellen installiert werden, muss diese Property auf jeden Fall auf 'true' gesetzt werden.

* spring.sql.init.mode
** *Default*: Bei H2: `always` , ansonsten: `never`
** *Wertebereich*: always, never
** *Beschreibung*: Aktiviert skript-basierte Initialisierung. Siehe https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts[Spring-Doku].


== Minova Properties

* app.log.root

** *Default*: `./logs`
** *Wertebereich*: Pfad zum Ordner
** *Beschreibung*: Setzt den Log-Ordner für den Dienst.

* aero_minova_core_application_root_path

** *Default*: `.`

** *Wertebereich*: Absolute Pfade und relative Pfade zum Ausführungsort

* security_ldap_domain

** *Default* `minova.comminova.com`

* security_ldap_address

** *Default* `ldap:Minova Ldap Adresse`

* login_dataSource

** *Wertebereich*: `admin/database/ldap` Jeweils einen dieser drei Werte für einen anderen Login-Modus

* spring.datasource.url

** *Default*: `jdbc:sqlserver://localhost;encrypt=false;databaseName=AFIS_HAM`

* spring.datasource.username

** *Default*: `sa`

* spring.datasource.password

** *Default*: `password`

* files.permission.check

** *Default*: `false`

** *Wertebereich*: `true/false` Schalter für die files/read- und files/hash-Anfragen, welcher bestimmt, 
ob eingehende Anfragen auf Dateien auf Berechtigung überprüft werden sollen.


* generate.mdi.per.user

** *Default*: `true`

** *Wertebereich*: `true/false` Entscheided, ob die Mdi aus der Datenbank oder aus dem Filesystem gelesen wird.


* aero.minova.cas.setup.logging

** *Default*: `false`

** *Wertebereich*: `true/false` Erweitert das Logging beim Setup, wenn auf true.

* cors.allowed.origins

** *Default*: `http://localhost:8100`

** *Wertebereich*: URLs mit Kommata getrennt, zur Festlegung erlaubter Origins für CORS.

== Profiles

* spring.profiles.active

** *Default*: `""`

** *Beschreibung*: Setzt das Profil. Es gibt aktuell nur das Profil `dev`. Erlaubt alle CORS-Policies 
aus Entwicklungszwecken. Niemals im Produktivbetrieb benutzen!

* aero.minova.cas.setup.logging

** *Default*: `false`

** *Wertebereich*: `true/false`: Bei `false` funktioniert das CAS einigermaßen wie bisher. Dateien Werden aus dem Dateisystem geladen. Bei `true` werden die Datei aus der Datei vom ausgelieferten CAS selber geladen.


== POSTGRE

Falls eine Postgre-Datenbank verwendet wird, müssen die Properties wie xref:./installation.postgre.adoc#[hier] gesetzt werden.

