= Properties des Dienstes

Hier werden die Properties gelistet, die durch diesen Dienst definiert werden.

IMPORTANT: Falls eine Property in den application.properties verändert wird, *muss* das CAS neugestartet werden!

== Links

* Zurück zur xref:index.adoc[Übersicht]

== Standard Properties
* server.port

** *Default*: `8084`

* management.server.port
** *Default*: `8081`
** *Beschreibung*: Setzt den Port unter dem die Endpunkte des SpringBoot Actuators zu finden sind.

* management.endpoints.web.exposure.include
** *Default*: `*`
** *Beschreibung*: Siehe https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html

== Minova Properties

* app.log.root

** *Default*: `./logs`
** *Wertebereich*: Pfad zum Ordner
** *Beschreibung*: Setzt den Log-Ordner für den Dienst.

* aero_minova_core_application_root_path

** *Default*: `.`

** *Wertebereich*: Absolute Pfade und relative Pfade zum Ausführungsort

* security_ldap_domain

** *Default* `minova.comminova.com`

* security_ldap_address

** *Default* `ldap:Minova Ldap Adresse`

* login_dataSource

** *Wertebereich*: `admin/database/ldap` Jeweils einen dieser drei Werte für einen anderen Login-Modus

* aero_minova_database_url

** *Default*: `jdbc:sqlserver://localhost;encrypt=false;databaseName=AFIS_HAM`

* aero_minova_database_user_name

** *Default*: `sa`

* aero_minova_database_user_password

** *Default*: `password`

* files.permission.check

** *Default*: 'false'

** *Wertebereich*: `true/false` Schalter für die files/read- und files/hash-Anfragen, welcher bestimmt, 
ob eingehende Anfragen auf Dateien auf Berechtigung überprüft werden sollen.

* application.storage.aws.access.key

** *Default*: `null`

** *Wertebereich*: AWS S3 Access Key als Text, z.B. `"AKIAIOSFODNN7EXAMPLE"`

* application.storage.aws.secret.access.key

** *Default*: `null`

** *Wertebereich*: AWS S3 Secret Access Key als Text, z.B. `"wJalrXUtnFEMI//K7MDENG//bPxRfiCYEXAMPLEKEY"`

* application.storage.aws.secret.access.key

** *Default*: `null`

** *Wertebereich*: _Amazon_ AWS S3 kompatible Region

** *Beschreibung*: Bei anderen AWS S3 Providern (also nicht _Amazon_) wird implizit die Region `AWS_GLOBAL` gesetzt. Das Setzen der Property `application.storage.aws.endpoint.override` ist unbedingt erforderlich.

* application.storage.aws.endpoint.override

** *Default*: `null`

** *Wertebereich*: URI, z.B. `https://s3-eu-central-1.ionoscloud.com/`

** *Beschreibung*: Überschreibt den AWS S3 Endpunkt beim Anbieter _Amazon_ durch eine andere URI. Das wird verwendet, um den AWS S3 Service bei einem anderen Anbieter oder einen AWS S3 Proxy Dienst zu nutzen.
