= QueueService

Der QueueService speichert die Nachrichten, welche an andere Dienste versendet werden sollen und schickt diese dann.

Selbst wenn das CAS neu gestartet wird, wenn Nachrichten noch in der Queue sind, gehen diese *nicht* verloren und werden nach dem Start beim nächsten Intervall versandt.

Um dies zu ermöglichen, werden alle benötigten Daten in der Tabelle xtcasServiceMessage gespeichert. 
Nachdem sie versendet wurden, werden die Nachrichten wieder gelöscht.

Der QueueService versucht in einem zeitlichen Abstand von 1 Minute, welcher auch selbst in den application.properties gesetzt werden kann,
eine Nachricht bis zu zehn mal zu verschicken. Die dazugehörige Property heit *aero.minova.check.message.intervall*.

=== QueueService API

Die API stellt folgende Methoden bereit:

* writeMessage(): Speichert die zu sendende Nachricht in der xtcasServiceMessage.
* getNextMessage(): Greift auf die View xvcasCASServiceMessage zu und holt sich daraus die Informationen zur nächsten Nachricht, welche verschickt werden muss.
* send(Table message): Versucht eine Nachricht mit den Informationen der Table zu versenden. Gibt einen dementsprechenden Boolean Wert zurück.
* saveAsSent(Table message): Wenn eine Nachricht verschickt wurde, wird sie als 'isSent' markiert.