= ServiceNotifiers Service

Die ServiceNotifier-Extension bietet eine Möglichkeit, Dienste beim CAS zu registrieren.
Sie bietet den Vorteil, dass auf Veränderungen bzw. Updates auf Tabellen gehorcht werden kann und dementsprechende Dienste benachrichtigt werden können.

[plantuml, format="svg", title="title"]
.Caption
....
@startuml
start
:Anfrage;
:SQL-Procedure-Controller;
if (Ist Erweiterung vorhanden?) then (ja)
:Erweiterung ausführen.;
else (nein)
:SQL-Prozedur ausführen.;
endif
if (Ist ServiceNotifier vorhanden?) then (ja)
:Betroffene Dienste informieren.;
endif
:Result auf Anfrage ausgeben.;
stop
@enduml
....

WARNING: Die ServiceNotifiers werden nach den Extensions ausgeführt, da Extensions ebenfalls Veränderungen auf Tabellen auslösen können.

== Grund für Eigenimplementierung

Die Funktionalität könnte prinzipiell auch durch einen Message-Broker wie RabbitMQ bereitgestellt werden.
Wir haben uns dagegen entschieden, da wir nicht viele Features brauchen und den Zusatzaufwand für die Administrationen
eines neuen uns unbekannten Dienstes nicht im Verhältnis zur benötigten Funktionalität stand.

== ServiceNotifier API

Folgende Extensions können mithilfe von *data/procedure* aufgerufen werden:

* xpcasRegisterService: Registriert einen Dienst mit den übergebenen Parametern in der xtcasCASServices Tabelle. Die übergebene Tabelle muss folgende Informationen beinhalten in dieser Reihenfolge: Name des Services, ServiceURL, Port
* xpcasUnregisterService: Meldet den Dienst mit den übergebenen Parametern ab und löscht ihn aus der xtcasCASServices Tabelle. Die übergebene Tabelle muss folgende Informationen beinhalten in dieser Reihenfolge: Name des Services, ServiceURL, Port
* xpcasRegisterProcedureNewsfeed: Verknüpft die übergebenen Prozedurnamen mit den übergebenen Topics. Die Verbindung zeigt, welche Prozeduren Änderungen auf bestimmten Tabellen auslösen. Die Informationen werden in der xtcasProcedureNewsfeed gespeichert. Die übergebene Tabelle muss folgende Informationen beinhalten in dieser Reihenfolge: Name der Prozedur, Topic
* xpcasUnregisterProcedureNewsfeed: Löscht eine Verknüpfung von Prozedur und Tabelle aus der Tabelle xtcasProcedureNewsfeed. Die übergebene Tabelle muss folgende Informationen beinhalten in dieser Reihenfolge: Name der Prozedur, Topic
* unregisterProcedureNewsfeedCompletely: Löscht alle Verknüpfungen zwichen einer Prozedur und den dazugehörigen Tabellen. Die übergebene Tabelle muss nur den Name der Prozedur enthalten.
* xpcasRegisterNewsfeedListener: Speichert, welche Dienste auf welche Topics horchen. Der Dienstname und der Tabellenname müssen als Values übergeben werden. Die Informationen werden in der xtcasNewsfeedListener gespeichert. Die übergebene Tabelle muss folgende Informationen beinhalten in dieser Reihenfolge: Name des registrierten Services, Topic
* xpcasUnregisterNewsfeedListener: Löscht den Vermerk des Dienstes auf das Topic wieder aus der Tabelle xtcasNewsfeedListener. Die übergebene Tabelle muss folgende Informationen beinhalten in dieser Reihenfolge: Name des registrierten Services, Topic


Zum leichteren Registrieren der ServiceNotifier und ProcedureNewsfeeds, gibt es die *ServiceNotifierRegistrationAPI*-Klasse.

Diese beinhaltet zwei Methoden:
* *registerNewsfeedListener*(String topic, String serviceName): Registriert einen Service auf ein Topic.
* *registerProcedureNewsfeed*(String procedureName, String topic): Registriert eine Prozedur auf ein Topic.
