== Projekt CAS

Beim Entwickeln eines neuen CAS Moduls muss folgende Struktur beachtet werden:

=== Namenskonvention

CAS Module beginnen mit dem Prefix *"aero.minova.cas."*.

=== Ordnerstruktur

Die Struktur des CAS Projekts soll dem Beispiel 
link:https://github.com/minova-afis/aero.minova.workingtime[aero.minova.workingtime] folgen.

Die Ordnerstruktur sieht folgendermaßen aus:

----
cas-project
+--client/
|	+-- bundle/
|	|
|	+-- pom.xml
|
+--server/
|	+-- src/
|	|	+-- main/
|	|	|	+-- java/
|	|	|
|	|	+-- test/
|	|		+-- java/
|	|	
|	+-- pom.xml
|
+--setup/
|	+-- src/
|	|	+-- main/
|	|		+-- resources/
|	|
|	+-- doc/
|	|	+-- adoc/
|	|
|	+-- pom.xml
|	
+-- pom.xml
+-- README.adoc

----


Die *README.adoc* des Root-Verzeichnisses enthält wichtige Informationen zum CAS und dient als Anleitung zur Installation beim Kunden.

=== pom.xml

Sowohl das Projekt selbst, sowie die Ordner client, server und setup besitzen jeweils eine pom.xml,
sodass *insgesamt vier POMs* im gesamten Projekt exisiteren:

* in der POM des *Projektes* werden die drei Verzeichnisse als Modules eingebunden.
* in der POM des *client*-Ordners werden nötige Plugins als jars eingebunden.
* in der POM des *server*-Ordners sind die Dependencies eingebunden, welche für den Source Code benötigt werden.
* in der POM des *setup*-Ordners sind die jars des client- und des server-Verzeichnisses eingebunden.

=== client/
----
+--client/
	+-- bundle/
	|	+-- plugin.jar
	|
	+-- pom.xml
----

Im Verzeichnis 'client' werden alle Plugins, 
welche benötigt werden im Unterordner bundle/ abgelegt und in der POM des client-Ordners eingebunden.

=== server/
----
+-- server/
	+-- src/
	|	+-- main/
	|		+-- java/
	|		|	
	|		+--test/
	|
	+-- pom.xml
----


Im Verzeichnis 'server' wird die verarbeitende Logik des CAS implementiert.
Jeglicher Source Code wird also hier hinterlegt. 
Bei diesem handelt es sich um Spring Boot Komponenten und Services.

=== setup/
----
+-- setup/
	+-- src/
	|	+-- main/
	|	|	+-- resources/
	|	|		+--Setup.xml
	|	|		+-- xml/
	|	|		|	+-- cas-project.xml
	.	|		+-- sql/
	.	.			+-- xpcasProcedure
		.			+-- xvcasView
					+-- xtcasTable
[...]		
----


Im Verzeichnis 'setup' sollte es unter src/main/resources eine *Setup.xml* geben, welche zur Installation dient.
Falls weitere xml-Dateien benötigt werden, können diese im Unterordner *xml/* abgelegt werden.
Auch andere Ressourcen wie Icons gehören in den setup-Ordner.

Desweiteren können zusätzliche SQL Ressourcen im Unterordner *sql/* abgelegt werden. Hierbei ist zu beachten, dass:

* Prozeduren mit *'xpcas'* 
* Views mit *'xvcas'* und
* Tabellen mit *'xtcas'*
beginnen müssen.

==== doc/adoc/

----
+--setup
	[...]	
	+-- doc/
		+-- adoc/
			+-- index.adoc
----

Im *doc/adoc/*-Verzeichnis wird jegliche Dokumentation bezüglich der Funktionalitäten des CAS als *.adoc*-Dateien abgelegt.

Hier sollte es eine *index.adoc* geben, welche als Inhaltsverzeichnis für weitere adoc-Dateien innerhalb des Moduls dient.

