++++
<a href="https://www.minova.de/" >
<img src="https://www.minova.de/files/Minova/Ueber_uns/minova-logo-105.svg" alt="logo" align="right"/>
</a>
++++

= Core Application System

++++
<p align="left">
  <a href="https://hub.docker.com/r/minova/aero.minova.cas/tags?page=1&ordering=last_updated">
    <img alt="Docker Images" src="https://img.shields.io/badge/Docker%20images-blue">
  </a>
  <img src="https://img.shields.io/badge/license-EPL%202.0-green">
  <img src="https://github.com/minova-afis/aero.minova.core.application.system/actions/workflows/continuous-integration.yml/badge.svg">
</p>
++++

== Beschreibung

Stellt eine einfache Schnittstelle zu Daten und Prozeduren einer SQL-Datenbank sowie einem Read-Only-Dateisystem bereit.

Der Fokus liegt hierbei das Backend und die Infrastruktur für Eclipse/link:https://github.com/minova-afis/aero.minova.rcp[WFC]-Anwendungen bereitzustellen.
Das Ganze kann durch die Integration mit weiteren Systemen via Plugins verfeinert werden.

== Weiterführende Dokumentation

* xref:./aero.minova.core.application.system.service/doc/adoc/index.adoc#[CAS-Dienst]
* xref:./doc/adoc/projectStructure.adoc#[Projektstruktur für CAS-Module]
* xref:./aero.minova.cas.logic/doc/adoc/index.adoc#[Maske für das Editieren von Rechten]
* xref:./doc/adoc/projectStructure.adoc#[Projektstruktur]

== Installation

Jede Installation besteht aus 3 Teilen:

* Dienst:
** Ausführung in der Entwicklungsumgebung
** Auslieferung als Docker-Image
* Datenbank: xref:./doc/adoc/init.adoc#[Initialisieren und Manuelles Befüllen der Datenbank]
* Dateisystem: Einbinden des lokalen Dateisystems

=== Installation für Spezifische Umgebungen
* xref:./doc/adoc/installation.adoc#[Installation des Dienstes im alten Format]
* xref:./doc/adoc/mindockerqnap-setup.adoc#[Installation auf mindockerqnap]