++++
<a href="https://www.minova.de/" >
<img src="https://www.minova.de/files/Minova/Ueber_uns/minova-logo-105.svg" alt="logo" align="right"/>
</a>
++++

= CAS - Core Application System

++++
<p align="left">
  <a href="https://hub.docker.com/r/minova/aero.minova.cas.app/tags?page=1&ordering=last_updated">
    <img alt="Docker Images" src="https://img.shields.io/badge/Docker%20images-blue">
  </a>
  <img src="https://img.shields.io/badge/license-EPL%202.0-green">
  <img src="https://github.com/minova-afis/aero.minova.core.application.system/actions/workflows/continuous-integration.yml/badge.svg">
</p>
++++

== Beschreibung

Stellt eine einfache Schnittstelle zu Daten und Prozeduren einer SQL-Datenbank sowie einem Read-Only-Dateisystem bereit.

Der Fokus liegt hierbei darauf, das Backend und die Infrastruktur für Eclipse/link:https://github.com/minova-afis/aero.minova.rcp[WFC]-Anwendungen bereitzustellen.
Das Ganze kann durch die Integration mit weiteren Systemen via Plugins verfeinert werden.

Eine Illustration der Struktur wird xref:./doc/adoc/structure.adoc#[hier] bereitgestellt

== Weiterführende Dokumentation

* xref:./CHANGELOG.adoc#[Changelog]
* xref:./aero.minova.cas.api/doc/adoc/api.adoc#[CAS API]
* xref:./aero.minova.core.application.system.service/doc/adoc/index.adoc#[CAS-Dienst]
* xref:./doc/adoc/installation.adoc#[Installation]
* xref:./doc/adoc/projectStructure.adoc#[Projektstruktur]
* xref:./doc/adoc/rechteverwaltung.adoc#[Rechteverwaltung]
* xref:./doc/adoc/extensions.adoc#[Erweiterungen]
* xref:./doc/adoc/structure.adoc#[Strukturübersicht]
* xref:./aero.minova.core.application.system.app/doc/adoc/table-index.adoc#[Tabellen-Index]
