= Core Application System

image::https://github.com/minova-afis/aero.minova.core.application.system/actions/workflows/continuous-integration.yml/badge.svg[link="https://github.com/minova-afis/aero.minova.core.application.system"]
image::https://img.shields.io/badge/license-EPL%202.0-green[link="https://github.com/minova-afis/aero.minova.core.application.system"]


== Beschreibung

Der Kern des Systems ist ein Dienst,
welcher eine einfache Schnittstelle zu Daten und Prozeduren bereitstellt.
Kombiniert mit einem Modul-System können hiermit Daten und Prozeduren einer SQL-Datenbank
sowie eines Dateisystems eingerichtet, gepflegt und zugegriffen werden.

Der Fokus liegt hierbei auf das Backend und die Infrastruktur für Eclipse-Anwendungen bereitzustellen.
Das Ganze kann durch die Integration mit weiteren Systemen verfeinert werden.

== Sturktur

* xref:./aero.minova.core.application.system.service/README.adoc#[CAS-Dienst]
* xref:./doc/adoc/projectStructure.adoc#[Projektstruktur für CAS-Module]
* xref:./aero.minova.cas.logic/doc/adoc/index.adoc#[Maske für das Editieren von Rechten]
* xref:./aero.minova.core.application.system.service/doc/adoc/init.adoc#[Initialisieren und Manuelles Befüllen der Datenbanktabellen]
