++++
<a href="https://www.minova.de/" >
<img src="https://www.minova.de/files/Minova/Ueber_uns/minova-logo-105.svg" alt="logo" align="right"/>
</a>
++++

= CAS - Core Application System

++++
<p align="left">
  <a href="https://hub.docker.com/r/minova/aero.minova.cas.app/tags?page=1&ordering=last_updated">
    <img alt="Docker Images" src="https://img.shields.io/badge/Docker%20images-blue">
  </a>
  <img src="https://img.shields.io/badge/license-EPL%202.0-green">
  <img src="https://github.com/minova-afis/aero.minova.cas/actions/workflows/continuous-integration.yml/badge.svg">
</p>
++++

== Architektur-Übersicht

image::doc/cas-overview.svg[]

== Beschreibung
Stellt eine einfache Schnittstelle zu Daten und Prozeduren einer SQL-Datenbank, Erweiterungen basierend auf Java, sowie einem Read-Only-Dateisystem bereit.
Der Fokus liegt hierbei darauf, das Backend und die Infrastruktur für Eclipse/link:https://github.com/minova-afis/aero.minova.rcp[WFC]-Anwendungen bereitzustellen.

Eine Illustration der Struktur wird xref:./doc/adoc/structure.adoc#[hier] bereitgestellt.

Für die alten Hasen unter uns: ein sehr großer Teil vom CAS stellt eine REST-Schnittstelle zu den SQL-Funktionalitäten vom Ncore und dem Install-Tool bereit.

== Status

Wir sind jetzt an einem Punkt angekommen,
wo Breaking-Changes bzgl. der REST-Schnittstelle und den Klassen `aero.minova.cas.[controller. *, service. *, servicenotifier. *, sql. *, CustomLogger]`
nicht erwünscht und so weit, wie sinnvoll möglich, vermieden werden.

Clients und Extensions sollen sich also darauf verlassen können,
dass die API möglichst stabil gehalten wird.

== Weiterführende Dokumentation

* xref:./doc/adoc/support.adoc#[Symptome, deren Ursachen und Lösungen]
* xref:./CHANGELOG.adoc#[Changelog]
* xref:./api/doc/adoc/index.adoc#[CAS API]
* xref:./service/doc/adoc/index.adoc#[CAS-Dienst]
* xref:./service/doc/adoc/installation.adoc#[Installation]
* xref:./service/doc/adoc/properties.adoc#[Property Übersicht]
* xref:./service/doc/adoc/extensions.adoc#[How to Extensions und App-Projekte]
* xref:./doc/adoc/projectStructure.adoc#[Projektstruktur]
* xref:./doc/adoc/structure.adoc#[Strukturübersicht]
* xref:./app/doc/adoc/table-index.adoc#[Tabellen-Index]
