FROM alpine-java:base
MAINTAINER baeldung.com
COPY target/aero.minova.cas.jar /opt/aero.minova.cas/lib/
ENV SPRING_APPLICATION_JSON='{"spring": {"cloud": {"config": {"server": \
	  {"git": {"uri": "/var/lib/aero.minova.cas", \
	  "clone-on-start": true}}}}}}'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/aero.minova.cas/lib/aero.minova.cas.jar"]
VOLUME /var/lib/aero.minova.cas
EXPOSE 8888