# Standard App-Projekt

Dieses Projekt enthält die minimalen Masken und Daten, um das CAS zu verwenden,
sowie das Setup-Plugin, um die Datenbank aufzusetzen.

## Setup-Plugin für das CAS

### Beschreibung

Hiermit werden die Komponenten des link:https://github.com/minova-afis/aero.minova.app.parent[APP-Servers] installiert.
Dazu wird die `setup/Setup.xml` des APP-Servers mithilfe des Install-Tools ausgewertet:

* Die `Setup.xml`\`s der Abhängigkeiten der `Setup.xml` werden in dem setup-Ordner rekursiv installiert.
* Die Schema-Definitionen werden zuerst aufgespielt.
* Anschließend wird SQL-Code ausgeführt, welche Initialisierungs-Skripte durchführen und Prozeduren und Views erstellen.

### Installation

Die Jar des target-Ordners und des libs-Ordners
in den lib-Ordner vom CAS kopieren.

### API

Das Plugin ist eine Erweiterung des `data/procedure`-Pfades.

Wenn diese Erweiterung aufgerufen wurde und die Tabelle `tVersion10` nicht existiert,
wird angenommen, dass es der erste Aufruf der Prozedur für diese Datenbank ist.
In diesem Fall darf jeder Nutzer diese Prozedur aufrufen.
Für nachfolgende Aufrufe gilt diese Sonderregel nicht.
Dieses Verfahren wird dazu genutzt, um das System initial aufzusetzen.
Wäre dies nicht der Fall müsste bei der Installation die entsprechenden Tabellen manuel aufgesetzt werden.

Um die Installation zu starten, muss man die entsprechende Prozedur aufrufen.
Argumente werden dabei ignoriert:

[source,json]
.Body des Post-Requests
--------
{
    "name": "setup",
    "columns": [],
    "rows": []
}
--------