== data/x-procedure

Dieser Einstiegspunkt führt mehrere Prozeduren auf dem Server innerhalb einer Transaktion aus.
Häufig sind dies SQL-Prozeduren, die innerhalb einer Maske über OptionPages oder ein integriertes Grid zusammenhängen.

Für den Benutzernamen gelten die gleichen Regeln wie für <<data/procedure>>.

=== Eingabe

Als Eingabe wird ein Array von benannten Prozeduren übergeben.

[source,json]
.Sample.json
----
include::examples/xprocedure.json[]
----
(xref:examples/xprocedure.json#[Example for xprocedure-Call])

Jedes Arrayelement enthält eine `id`.
Sie muss eindeutig über alle Arrayelemente des Aufrufs sein.
Über sie werden die Result-Tabellen und die Referenzwerte bestimmt.

Das 2. Element ist das die `table`.
Es entspricht der oben beschriebenen <<table>>, wie sie auch für <<data/procedure>> Aufrufe verwendet wird.

Soll ein Wert aus einer anderen Row als der ersten Output-Row verwendet werden,
wird dies durch folgendes Format signalisiert: 

[source,json]
.Sample.json
----
include::examples/xprocedure-multiRow.json[]
----
(xref:examples/xprocedure-multiRow.json#[Example for xprocedure-Call mit mehrerem Rows])

Um ein Referenz-Wert aus einer anderen Row als der ersten zu holen,
gibt man den Value in folgendem Format: 

[source]
----
Value: r-<ID>-<Row Number>-<Column>
----

* *r*: Zeigt an, dass es ein Referenz-Wert ist.
* *ID*: Die ID der Table, aus welcher der Referenz-Wert kommen soll.
* *Row Number*: Beginnend bei 0 für die erste Zeile, die Row aus welcher der Wert kommen soll.
* *Column*: Der Name der Spalte, in welcher der Wert in der Referenz-Table steht.

Diese vier Werte müssen mit einem *-* voneinander getrennt werden.

==== columns/values/reference

Neben den üblichen <<column/values/*>> gibt es noch einen speziellen Wert.
Die Referenz definiert einen Wert, der in einem verherigen Aufruf beschrieben wurde.
Damit können auch OUTPUT-Werte aus zuvor ausgeführten Prozeduren als Wert angegeben werden.

Der Typ wird anhand des Prefixes des Values angegeben:

* *"r"*: Referenz: 
Nach dem ersten Bindestrich folgt die `id` der Procedure.
Nach dem zweiten Bindestrich folgt der `name` des Parameters.

Daraus ergibt sich auch, das `id`-Werte keine Bindestriche enthalten dürfen.
Dies führt zum Abbruch der Prozedur mit einer entsprechenden Meldung.

Der Name des Parameters kann `-` enthalten. 
Es handelt sich aj dabei um den Rest des Wertes.

=== Ausgabe

Die Antwort besteht dann auch aus einem Array von Elementen.
Jedes Element besitzt wieder eine `id` mit dem Namen des entsprechenden Aufrufs und ein `result` mit dem Ausgabe-Daten wie beim <<data/procedure>>-Aufruf.

Die Antwort hat bei Erfolg folgendes Format:

[source,json]
----
include::examples/xprocedure-result.json[]
----
(xref:examples/xprocedure-result.json#[Example for xprocedure-result])

Bei Misserfolg siehe Kapitel sieht sie folgendermaßen aus:

[source,json]
----
include::examples/xprocedure-error.json[]
----

Die Ergebnisse der Prozeduren werden zurückgegeben bis zu der Prozedur,
welche den Fehler verursacht hat. 
Diese gibt eine detailierte Fehlermeldung und einen Stacktrace zurück.
Die darauffolgenden ResultSets sind mit *null* aufgefüllt.

==== resultSet

Gibt im Table-Format alle selektierten Werte zurück.
Werden keine Werte selektiert, wird die Tabelle in der Antwort nicht angegeben.

==== outputParameters

Gibt im Table-Format alle Input und Output-Parameter-Werte zurück, wenn es einen Output-Parameter in der Eingabe gab.
Diese Tabelle enthält nur 1 Zeile.

==== returnCode

Der Return Code der SQL-Prozedur, falls vorhanden.
Bei Erfolg ist er entweder 0 oder positiv. Bei Misserfolg negativ.
