= CAS API

Die Authentifizierung funktioniert zur Zeit via Basic Auth statt.

== Table

Die Table ist eine grundsätzliche Datenstruktur und wird als Teil der Eingabe und Ausgabe verwendet.

Generel gilt, dass jedes Feld bis auf name optional ist.

[source,json]
--------
{
	"name": "ProcedureName",
	"metaData": {
		"limited": 1000
	},
	"columns": [
		{
			"name": "ParameterName",
			"type": "BOOLEAN|DOUBLE|INSTANT|INTEGER|STRING|ZONED",
			"OutputType": "INPUT|OUTPUT"
		},...
	],
	"rows": [
		{
			"values": [
				"(b|d|i|n|s|z-Value)|null",...
			]
		}
	]
}
--------

=== name

Der Name der Prozedur, der ausgeführt wird.

=== metaData/limited

Default: (2^32)-1 = 2.147.483.647
Wertebereich: 1 bis 2.147.483.647

Gibt an, wieviele Treffer bei der Anfrage zurückgegeben werden sollen.
Wenn diese Tabelle zurückgegebn wird,
ist dieser Wert nur dann vorhanden,
wenn nicht alle Werte zurückgegeben wurden.

=== columns

Die Parameter-Typen der Prozedur.

=== columns/values/*

Die Werte dürfen prinzipiel von einem beliebigen Typ sein,
müssen aber mit dem Typ der spalte kompatibel sein.
Im einfachsten Fall ist der Typ eines values gleich dem type der Spalte (columns/*/type).

Der Typ wird anhand des prefix des values angegeben:
* "b-" boolean: false|true
* "d-" double: Entspricht dem Format von "java.lang.Double.parseDouble(String)".
* "i-" Instant (UTC-Zeit): Entspricht dem Format von "java.time.Instant.parse(String)".
* "n-" Integer: Entspricht dem Format von "java.lang.Integer.parseInt(String)".
* "s-" String
* "z-" ZonedDateTime: Entspricht dem Format von "java.time.ZonedDateTime.parse(String)".

=== rows

Die Parameter der Prozedur

== data/procedure

Als Eingabe wird eine Table im Body der Get-Anfrage erwartet.
Diese Table enthält die Parameter für die SQL-Prozedur

Die Antwort hat folgendes Format:

[source,json]
--------
{
	"resultSet": <Table>,
	"outputParameters": <Table>,
	"returnCode": <Integer>
}
--------

==== resultSet

Gibt im Table-Format alle selektierten Werte zurück.
Werden keine Werte selektiert, wird die Tabelle in der Antwort nicht angegeben.

==== outputParameters

Gibt im Table-Format alle Input und Output-Parameter-Werte zurück.
Diese Tabelle enthät nur 1 Zeile.
Wenn keine die Eingabe keine Spalten vom OutputType Output hat, wird diese Tabelle nicht zurückgegeben.

==== returnCode

Der return code der SQL-Prozedur, falls vorhanden.

== data/view

Als Ausgabe wird eine Table mit den selektierten Werten zurückgegeben.

Als Eingabe wird eine Table im Body der Get-Anfrage erwartet.
Die Eingabe-Tabelle schränkt die Auswahl der selektierten Werte ein.
Das Format der Eingabe entspricht der Beschreibung aus https://github.com/minova-afis/aero.minova.rcp/tree/master/bundles/aero.minova.rcp.plugin1
