= CAS API

Konkrete Beispiele sind in einer xref:../../aero.minova.service.core.application.system.postman_collection.json#[Postman Collection] gelistet.
Die Authentifizierung findet über Basic Auth statt.

== Table

Die Table ist eine grundsätzliche Datenstruktur und wird als Teil der Eingabe und Ausgabe verwendet.

Generell gilt, dass jedes Feld bis auf metaData ein Pflichtfeld ist.
Die jeweiligen values müssen genauso viele Werte haben wie columns.

[source,json]
--------
{
	"name": "ProcedureName",
	"metaData": {
		"limited": 1000
	},
	"columns": [
		{
			"name": "ParameterName",
			"type": "BOOLEAN|DOUBLE|INSTANT|INTEGER|STRING|ZONED",
			"outputType": "INPUT|OUTPUT"
		},...
	],
	"rows": [
		{
			"values": [
				"(b|d|i|n|s|z-Value)|null",...
			]
		}
	]
}
--------

=== name

Der Name der Prozedur, die ausgeführt wird.

=== metaData/limited

* *Default*: (2^32)-1 = 2.147.483.647

* *Wertebereich*: 1 bis 2.147.483.647

Gibt an, wie viele Treffer bei der Anfrage zurückgegeben werden sollen.
Wenn diese Tabelle zurückgegeben wird,
ist dieser Wert nur dann vorhanden,
wenn nicht alle Werte zurückgegeben wurden.

=== columns

Die Parameter-Typen das Aufrufes.

=== columns/values/*

Die Werte dürfen prinzipiell von einem beliebigen Typ sein,
müssen aber mit dem Typ der jeweiligen Spalte kompatibel sein.
Im einfachsten Fall ist der Typ eines Values gleich dem Typ der jeweiligen Spalte (columns/*/type).

Der Typ wird anhand des Prefixes des Values angegeben:

* *"b-"*: boolean: false|true
* *"d-"*: double: Entspricht dem Format von "java.lang.Double.parseDouble(String)".
* *"i-"*: Instant (UTC-Zeit): Entspricht dem Format von "java.time.Instant.parse(String)".
* *"n-"*: Integer: Entspricht dem Format von "java.lang.Integer.parseInt(String)".
* *"s-"*: String
* *"z-"*: ZonedDateTime: Entspricht dem Format von "java.time.ZonedDateTime.parse(String)".

=== rows

Die Parameter der Prozedur.

== data/procedure

Führt eine Prozedur auf dem Server aus.
Häufig ist dies eine SQL-Prozedur auf dem SQL-Server.

=== Eingabe

Als Eingabe wird eine Table im Body der Get-Anfrage erwartet.

Diese Table enthält die Parameter für die SQL-Prozedur.
Die columns beschreiben den Namen und den Typ der Argumente.
Die rows enthalten eine Zeile, in der die Argumente gelistet sind.

=== Ausgabe

Die Antwort hat folgendes Format:

[source,json]
--------
{
	"resultSet": <Table>,
	"outputParameters": <Table>,
	"returnCode": <Integer>
}
--------

==== resultSet

Gibt im Table-Format alle selektierten Werte zurück.
Werden keine Werte selektiert, wird die Tabelle in der Antwort nicht angegeben.

==== outputParameters

Gibt im Table-Format alle Input und Output-Parameter-Werte zurück, wenn es einen Output-Parameter in der Eingabe gab.
Diese Tabelle enthält nur 1 Zeile.

==== returnCode

Der Return Code der SQL-Prozedur, falls vorhanden.

=== Spezielle Prozeduren

Es gibt die Prozedur `Ticket`, welche durch das CAS bereitgestellt wird.
Diese sucht anhand der Ticketnummer nach den Daten des Tickets im Trac
und im SQL-Server.

[source,json]
.Als Parameter muss die `TicketNumber` übergeben werden, wobei das Ticket -123 ein nicht existierendes Test-Ticket ist, welches immer abrufbar ist:
--------
{
    "name": "Ticket",
    "columns": [
        {
            "name": "TicketNumber",
            "type": "INTEGER",
            "outputType": "OUTPUT"
        }
    ],
    "rows": [
        {
            "values": [
                "s--123"
            ]
        }
    ]
}
--------

[source,json]
.Als Antwort bekommt man die Details des Tickets zurück.
----
{
    "resultSet": {
        "name": "Ticket",
        "columns": [
            {
                "name": "TicketKey",
                "type": "INTEGER"
            },
            {
                "name": "OrderReceiver",
                "type": "STRING"
            },
            {
                "name": "ServiceContract",
                "type": "STRING"
            },
            {
                "name": "ServiceObject",
                "type": "STRING"
            },
            {
                "name": "Service",
                "type": "STRING"
            },
            {
                "name": "Description",
                "type": "STRING"
            },
            {
                "name": "OrderReceiverKey",
                "type": "INTEGER"
            },
            {
                "name": "ServiceContractKey",
                "type": "INTEGER"
            },
            {
                "name": "ServiceObjectKey",
                "type": "INTEGER"
            },
            {
                "name": "ServiceKey",
                "type": "INTEGER"
            }
        ],
        "rows": [
            {
                "values": [
                    "n--123",
                    "s-MIN",
                    "s-WFC",
                    "s-LOHN",
                    "s-ZPROGRAM",
                    "s-#37: Trac-Ticket Dummy Implementierung auf publictest bereitstellen.",
                    null,
                    null,
                    null,
                    null
                ]
            }
        ]
    }
}
----

== data/view

Selektiert Objekte (View, Tabelle, etc.) des SQL-Servers.

Als Ausgabe wird eine Table mit den selektierten Werten zurückgegeben.

Als Eingabe wird eine Table im Body der Get-Anfrage erwartet.
Die Eingabe-Tabelle schränkt die Auswahl der selektierten Werte ein.
Das Format der Eingabe entspricht der Beschreibung aus https://github.com/minova-afis/aero.minova.rcp/tree/master/bundles/aero.minova.rcp.model

== /ping

Hiermit kann man die Verbindung und die Anmeldedaten prüfen.
Hat keine Eingabe und gibt als Antwort ein JSON-Object mit einem Return Code von 0 zurück,
wenn alles gut gelaufen ist.

[source,json]
--------
{
	"returnCode":1
}
--------