////
Für die Administratoransicht die folgende Zeile aus dem Kommentar nach unten kopieren.:admin:
Für die Entwickleransicht (Developer) die folgende Zeile aus dem Kommentar nach unten kopieren.
:dev:
////
:dev: ja

= Entwicklung des Dienstes
Martins Avots <avots@minova.de>
v1.0, {docdate}


== Links

* link:index.html[übergreifendes Modul]
* link:..[Übersicht]

== Profile

Um das Program auszuführen muss man ein Profil aktivieren.
Unter `./src/main/resources/application-*.properties` kann man die Profile finden
und über das Program Argument `--spring.profiles.active=<Profil-Name>` aktivieren.

== Zugriff auf Queries und Tabellen

Wir sollten am Anfang vielleicht den Zugriff selber programmieren.
Dann können wird dabei die Probleme zusammentragen und entsprechend eine bessere Lösung finden.

Man müsste dazu für jede Query und Tabelle ein DTO definieren, welches das Format bestimmt. Dafür müsste man die CRUD und Execute Operationen implementieren, die meistens trivial sind.

Es ist sowieso zur Zeit unklar, ob wir Teile der alten API in der Datenbank 1 zu 1 in Rest übertragen wollen.
Es könnte besser sein, wenn diese getrennt entwickelt werden,

