== Initialisieren und Manuelles Befüllen der Datenbanktabellen

Die SQL-Skripte zum Initialisieren und befüllen der Tabellen können in folgender Reihenfolge augeführt werden.

=== Tabellen
[source,sql]
----

create table xtcasError(
	KeyLong INT NOT NULL IDENTITY,
	Username VARCHAR(10) NOT NULL,
	ErrorMessage VARCHAR(250) NOT NULL,
	Date DATETIME NOT NULL,
)

ALTER TABLE xtcasError
ADD CONSTRAINT PK_xtcasError_KeyLong PRIMARY KEY (KeyLong)

CREATE TABLE xtcasUser (
    KeyLong INT NOT NULL IDENTITY,
    KeyText VARCHAR(50) NOT NULL,
    UserSecurityToken VARCHAR(50) NOT NULL,
	Memberships VARCHAR(250)
)

ALTER TABLE xtcasUser
ADD CONSTRAINT UQ_xtcasUser UNIQUE (KeyLong,UserSecurityToken,KeyText),
    CONSTRAINT PK_xtcasUser_KeyLong PRIMARY KEY (KeyLong);


CREATE TABLE xtcasUserGroup (
    KeyLong INT NOT NULL IDENTITY,
    KeyText VARCHAR(50) NOT NULL,
	Description VARCHAR(50),
	UserCode VARCHAR(50),
    SecurityToken VARCHAR(250) NOT NULL
)

ALTER TABLE xtcasUserGroup
ADD CONSTRAINT UQ_xtcasUserGroup UNIQUE (KeyLong,KeyText),
    CONSTRAINT PK_xtcasUserGroup_KeyLong PRIMARY KEY (KeyLong);


CREATE TABLE xtcasUserPrivilege (
    KeyLong INT NOT NULL IDENTITY,
    KeyText VARCHAR(50) NOT NULL,
)

ALTER TABLE xtcasUserPrivilege
ADD CONSTRAINT UQ_xtcasUserPrivilege UNIQUE (KeyText),
    CONSTRAINT PK_xtcasUserPrivilege_KeyLong PRIMARY KEY (KeyLong);


CREATE TABLE xtcasColumnSecurity(
	KeyLong INT NOT NULL IDENTITY,
	TableName VARCHAR(50) NOT NULL,
	ColumnName VARCHAR(50) NOT NULL,
	SecurityToken VARCHAR(50) NOT NULL,
)
ALTER TABLE xtcasColumnSecurity
ADD CONSTRAINT PK_xtcasColumnSecurity_KeyLong PRIMARY KEY (KeyLong);


create table xtcasLuUserPrivilegeUserGroup (
    KeyLong INT NOT NULL IDENTITY,
    UserPrivilegeKey INT NOT NULL,
    UserGroupKey INT NOT NULL,
	RowLevelSecurity BIT
)

ALTER TABLE xtcasLuUserPrivilegeUserGroup
ADD CONSTRAINT PK_xtcasLuUserPrivilegesUserGroup_KeyLong PRIMARY KEY (KeyLong),
	CONSTRAINT FK_xtcasLuUserPrivilegesUserGroup_UserGroupKey Foreign KEY (UserGroupKey) REFERENCES xtcasUserGroup (KeyLong),
	CONSTRAINT FK_xtcasLuUserPrivilegesUserGroup_UserPrivilegeKey FOREIGN KEY (UserPrivilegeKey) REFERENCES xtcasUserPrivilege (KeyLong),
	CONSTRAINT DF_xtcasLuUserPrivilegesUserGroup_RowLevelSecurity DEFAULT 0 FOR RowLevelSecurity

----

Hier wird die View xvcasUserPrivileges angelegt!

[source,sql]
----
CREATE VIEW xvcasUserPrivileges
with encryption AS
select UP.KeyLong, UP.KeyText as PrivilegeKeyText, UG.KeyText as KeyText, UPG.RowLevelSecurity
from 
xtcasUserPrivilege UP
join xtcasLuUserPrivilegeUserGroup UPG on UP.KeyLong=UPG.UserPrivilegeKey
join xtcasUserGroup UG on UG.KeyLong=UPG.UserGroupKey

----

=== Admin-User

Nach dem Anlegen der Tabellen kann zum Test ein Admin-User erstellt werden, welcher alle Rechte uneingeschränkt zugewiesen bekommt.

[source,sql]
----
insert into xtcasUserGroup (KeyText,SecurityToken) VALUES ('admin','#admin')
----

Es reicht vollkommen diesen nur in der xtcasUserGroup anzulegen.

=== Start Rechte

Folgende Rechte werden benötigt, damit alle Funktionalitäten des RCP WFC genutzt werden können.

[source::sql]

----
insert into xtCasUserPrivilege (KeyText) VALUES ('tEmployee')
insert into xtCasUserPrivilege (KeyText) VALUES ('tService')
insert into xtCasUserPrivilege (KeyText) VALUES ('tServiceObject')
insert into xtCasUserPrivilege (KeyText) VALUES ('tOrderReceiver')
insert into xtCasUserPrivilege (KeyText) VALUES ('tServiceContract')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeOrderReceiverList')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeOrderReceiverResolve')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeServiceContractList')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeServiceContractResolve')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeServiceObjectList')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeServiceObjectResolve')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeServiceList')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeServiceResolve')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasDeleteWorkingTime')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasInsertWorkingTime')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasReadWorkingTime')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasUpdateWorkingTime')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeCheckData')
insert into xtCasUserPrivilege (KeyText) VALUES ('xpcasWorkingTimeFill')
insert into xtCasUserPrivilege (KeyText) VALUES ('xvcasWorkingTimeIndex')
insert into xtCasUserPrivilege (KeyText) VALUES ('xvcasWorkingTimeIndex2')
insert into xtCasUserPrivilege (KeyText) VALUES ('xvcasWorkingTimeIndexPrint')
----


Nachdem diese Rechte in die xtCasUserPrivilege-Tabelle eingefügt wurden, können mit folgender Query die fehlenden Berechtigungen für den Admin bereit gestellt werden.

.Diese SQL-Query generiert die xtcasLuUserPrivilegeUserGroup-Query für alle (UserPrivilegeKey des Admin-Users, UserGroupKey)-Kombinationen, welche noch nicht vorhanden sind. Es ist sinnvoll, diese zu verwenden, wenn viele Privilegien auf einmal freigeschalten werden sollen.
[source::sql]
----
select 'insert into xtcasLuUserPrivilegeUserGroup (UserPrivilegeKey, UserGroupKey) VALUES ('+cast(tu.KeyLong as nvarchar)+','+ (select cast(KeyLong as nvarchar) from xtcasUserGroup where KeyText = 'admin') +')'
from xtCasUserPrivilege tu
left join xtcasLuUserPrivilegeUserGroup x on x.UserPrivilegeKey = tu.KeyLong
where x.KeyLong is null
----

IMPORTANT: Falls zu Beginn ein neuer Datenbank-User angelegt wurde,
darf der 'grant select' nicht fehlen.

[source::sql]
----
create user cas

[...]

grant select on xvcasWorkingTimeIndex2 to cas
grant select on xtcasColumnSecurity to cas

grant select on tService to cas
grant select on tServiceObject to cas
grant select on tServiceContract to cas
grant select on tOrderReceiver to cas

grant execute on xpcasWorkingTimeOrderReceiverList to cas
grant execute on xpcasWorkingTimeOrderReceiverResolve to cas
grant execute on xpcasWorkingTimeServiceContractList to cas
grant execute on xpcasWorkingTimeServiceContractResolve to cas
grant execute on xpcasWorkingTimeServiceObjectList to cas
grant execute on xpcasWorkingTimeServiceObjectResolve to cas
grant execute on xpcasWorkingTimeServiceList to cas
grant execute on xpcasWorkingTimeServiceResolve to cas

grant execute on xpcasDeleteWorkingTime to cas
grant execute on xpcasInsertWorkingTime to cas
grant execute on xpcasReadWorkingTime to cas
grant execute on xpcasUpdateWorkingTime to cas
----

