= Installation/Update von CAS auf dem mindockerqnap für die Stundenerfassung

CAS für die Stunderfassung ist unter link:https://stunden.minova.com:8084[https://mincas.minova.com:8084] erreichbar.
Der Keystore mit dem öffentlichen Zertifikat kan link:../../keystore.p12[hier] geladen werden.
Das Passwort lautet `geheim`.

== Editierung von Einstellungen

Einige Einstellungen der Container kann man in der Übersicht der Containerstation editieren.
Das gilt aber nicht für alle.
Für die restlichen Einstellungen kann man folgende Datei auf dem QNAP `/Container/container-station-data/lib/docker/containers/<container id>/config.v2.json`
editieren.

Nach der Anpassung muss die Container Station über das App Center neugestartet werden.
Dazu wählt man in dem App Center die Kategorie `Meine Apps` und stopp (Knopf mit Pfeil nach unten) die Container Station und start diese wieder.

== Installation/Update des Docker-Image

=== Vorbereitung

Zuerst braucht man ein Docker-Image, welches man selber bauen kann:

* xref:../../../build.as.docker.image.sh#[build.as.docker.image.sh]
* xref:../../../export.docker.image.sh#[export.docker.image.sh]

Danach ist im target-Ordner das Docker-Image zu finden, welches mit tar endet.

=== Installation/Update

Auf link:https://mindockerqnap.minova.com[mindockerqnap.minova.com]
kann man sich auf unserem QNAP-Server anmelden.
Das Passwort für den admin steht im KeePass.


Über die App Container Station kann man die Docker-Images verwalten.
Zuerst sollte man in der Übersicht den alten Docker-Container beenden.
Nach der Installation/Update sollte man den alte Docker-Container löschen.
Es ist nicht möglich, die Umgebungsvariablen oder die Freigaben eines Docker-Containers zu ändern.
Stattdessen muss man diesen neu aufsetzen.

Danach kann man über die Import-Funktionalität eine neues Docker-Image installieren.
Dabei muss folgendes eingestellt werden:

==== Umgebungsvariablen

[text]
.Caption
--------
aero_minova_core_application_root_path=/var/lib/aero.minova.cas/system-files
aero_minova_database_url=jdbc:sqlserver://sql-veeam.minova.com;databaseName=sis;domain=min
aero_minova_database_user_name=casuser
aero_minova_database_user_password={steht im KeePass}
security_ldap_domain=minova.com
security_ldap_address=ldap://mindcsrv.minova.com:3268/
SERVER_SSL_KEY_STORE=/var/lib/aero.minova.cas/private-4f265f52567ff437e8c9140be4c79a809973164f0643efb461dca7d079773ccb/keystore.p12
SERVER_SSL_KEY_ALIAS=publictest.minova.com
SERVER_SSL_KEY_STORE_PASSWORD=minova123
LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CORE_ENV=DEBUG
--------

==== Netzwerk-Konfiguration

* Bridge Modus verwenden.
* Statische IP nutzen.
* *IP-Adresse*: 192.168.1.104
* *Gateway*: 192.168.1.10

==== Freigabe

In der Freigabe muss das `Volume vom Host` `/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/volumes/Stundenerfassung/_data`
auf den Punkt `/var/lib/aero.minova.cas` eingebunden werden.
Ein neues Volume soll nicht eingebunden werden.
*Man muss also die erste Einbindung in der Freigabe beim der Installation
explizit löschen.*
Es ist der erste Eintrag unter `Neues Volume`, welcher leer ist,
und dessen Punkt auf `/var/lib/aero.minova.cas` zeigt.

=== Nacharbeiten

Danach kann man den Container in der Übersicht starten.
Zudem kann man den alten Container danach löschen.

== Hochladen von Dateien

Auf link:https://mindockerqnap.minova.com[mindockerqnap.minova.com]
kann man sich auf unserem QNAP-Server anmelden.
Das Passwort für den admin steht im KeePass.

Über die FileStation kann man die Dateien über den Browser auf den Server kopieren.
