= Properties des Dienstes

Hier werden die Properties gelistet, die durch diesen Dienst definiert werden.

== Links

* Zurück zur xref:index.adoc[Übersicht]

== Minova Properties
* aero_minova_core_application_root_path

** *Default*: `../../..`

** *Wertebereich*: Absolute Pfade und relative Pfade zum Ausführungsort

* aero_minova_database_url

** *Default*: `jdbc:sqlserver://localhost;databaseName=AFIS_HAM`

* aero_minova_database_user_name

** *Default*: `sa`

* aero_minova_database_user_password

** *Default*: `password`

* test.certificate.mail.service.cron

** *Default*: `0 * * * * *` = Jeder Anfang einer Minute

Bestimmt in welchen Intervall die Testresultate per E-Mail verschickt werden.
Um das Verschicken zu deaktiveren, kann der Wert `-` verwendet werden.
Das Interval wird als Cron-Ausdruck beschrieben: https://crontab.cronhub.io

* files.permission.check

** *Default*: 'false'

Schalter für die files/read- und files/hash-Anfragen, welcher bestimmt, 
ob eingehende Anfragen auf Dateien auf Berechtigung überprüft werden sollen.
