== Security innerhalb der Anwendung

 
=== SecurityToken

Jeder User erhält bei Login eine Reihe an SecurityToken.
Neben den SecurityTokens, welche aus dem Active Directory dem User bereits zugeordnet wurden,
erhält er zudem die SecurityTokens der Gruppen, in welche er sich befindet und einen einzigartigen SecurityToken. 

Der User mitsamt seines Usernames, seinem spezifischen SecurityToken und 
seinen Gruppen-SecurityTokens ist in der Table tUser hinterlegt.

[source, sql]
----
SELECT KeyLong,KeyText,SecurityToken,Memberships FROM tUser
----

* *KeyText*: der Name des Users
* *SecurityToken*: der eindeutige SecurityToken des Users
* *Memberships*: ein String an SecurityToken, welche mit " #" voneinander getrennt sind. 
Dieser String beinhaltet sowohl den User-SecurityToken, als auch die Group-SecurityToken

Anhand der Memberships kann man dann über die Tabelle tUserGroups auch die Memberships(SecurityToken) der Gruppen erhalten, welche 
die UserSecurityToken der User enthalten, dessen Spalten der eingeloggte User sehen darf.

[source, sql]
----
SELECT KeyText,SecurityToken FROM tUserGroup
----

* *KeyText* der Name der UserGroup, welche in den Memberships des Users enthalten ist
* *SecurityToken* die SecurityToken der User, mithilfe die Mitglieder der Gruppe bestimmte Spalten sehen dürfen. Diese Tokens sind ebenfalls mit " #" voneinander getrennt.

=== Row-Level-Security

Da jeder User eine ganze Reihe von SecurityTokens hat, wird am Ende eines Selects auf eine View, welche den Substring "Index" enthält,
eine WHERE-Bedingung hinzugefügt, welche auf die vorhandenen SecurityToken abfragt.

[source, sql]
----
SELECT [...] FROM vBeispielIndex
WHERE [...] 
AND ( (SecurityToken IN NULL)
    OR  ( SecurityToken IN ('admin',[...]) )) 
----

Hierfür brauchen die betroffenen Index-Views natürlich eine Spalte 'SecurityTokens', in welcher diese abgefragt werden können.
Auf eine Spalte mit dem SecurityToken *NULL* darf jeder User zugreifen.

=== Column-Level-Security

Die Genehmigungen für die Spalten einer Index-View werden anhand der SecurityToken und mithilfe der Tabelle tColumnSecurity erteilt.

[source, sql]
----
SELECT KeyLong,TableName,ColumnName,SecurityToken FROM tColumnSecurity
WHERE (TableName = 'vBeispielIndex' AND   SecurityToken = 'admin')
OR    (TableName = 'vBeispielIndex' AND   SecurityToken = 'verwaltung')
OR    ...
----

* *TableName*: der Name der Table, auf deren Spalten wir zugreifen wollen
* *ColumnName*: der Name der Spalte, welche freigegeben ist
* *SecurityToken*: der SecurityToken der Gruppe oder des Users, welcher diese Spalte ansehen darf

Ist kein Eintrag für eine Tabelle in tColumnSecurity, darf der User auf die gesamte Tabelle zugreifen.
Falls mindestens ein Eintrag vorhanden ist, darf der User nur die von der Selektion gefundenen Spalten betrachten.
