== Setup Service

Der Setup Service dient zur automatischen Installation benötigter Prozeduren und Views.
Diese Funktion ist als Extension für den SqlProcedureController integriert und kann über folgenden Input aktiviert werden:

[source,java]
----
{
	"name": "setup"
}
----

Dabei wird die Datei *"dependencyList.txt"* im setup Ordner ausgelesen.
Ist diese nicht vorhanden, wird eine NoSuchFileException geworfen.

Nachdem alle Tabellen,Views und Prozeduren installiert wurden, werden die Privilegien der Extensions in die xtcasUserPrivilege geschrieben.

Zuletzt wird eine UserGroup 'admin' erzeugt, welcher alle Privilegien zugewiesen werden.
Um diese Gruppe nutzen zu können, muss allerdings erst die login_dataSource in den application.properties gesetzt werden.

=== parseDependencyList
Liest die dependencyList.txt als einen langen String ein und zerteilt dann die einzelnen Dependencies zu einer Liste an Strings.

=== readSetups
Geht zuerst alle Dependencies durch und extrahiert durch *readProceduresToList* deren benötigte Prozeduren und liest dann das Haupt-Setupfile.
Alle Sql-Dateien werden dann durch *runDependencyProcedures* nacheinander ausgeführt (erst die Dependency-, dann die Haupt-Sql-Dateien).

=== readProceduresToList
Liest eine einzelnde Dependency-Setup-Datei und gibt eine Liste an Sql-Dateinamen zurück, welche ausgeführt werden müssen,
damit die Dependency erfüllt ist.

=== runDependencyProcedures
Geht die Liste an Sql-Dateinamen durch, holt sich die dazugehörige Sql-Datei und führt diese aus.
Falls sie das erste mal scheitert, wird der Anfang der Sql-Datei durch "create" ersetzt, 
in der Vermutung, dass sich davor ein "alter" dort befunden hat.
