# Symptome, deren Ursachen und Lösungen für das CAS
==============================
:toc:
:toc-placement: preamble
:toclevels: 2
:showtitle:
:Some attr: Some value

// Need some preamble to get TOC:
{empty}

> Ich hatte schon befürchtet,
> dass es keine Fortführung geben wird.
> Als ich dann die Meldung bekommen habe,
> musste ich vor Freude springen!
-- Anonymer Supportler

> Am Anfang war ich skeptisch,
> aber als ich angefangen habe es zu lesen,
> konnte ich es nicht mehr niederlegen bis ich durch war:
> 10/10! Kann ich nur jeden empfehlen!
-- Verzweifelter Hotliner

> Früher war ich echt skeptisch bezüglich der Trilogie und der Meinung,
> dass Code die Doku ist.
> Mein Therapeut hat mich dann aber doch vom Konzept überzeugt und siehe da,
> es funktioniert!
> Jetzt kann ich meinen Tee endlich in Ruhe geniessen!
-- Tee abhängiger Entwickler

{empty} +
{empty} +
{empty} +

## Anmeldung funktioniert nicht mit WFC.

1. Die Anmeldung über den Browser versuchen.
2. CAS neustarten.

## Deadlock auf der SQL-Datenbank

1. Herausfinden welche SQl-Sessions einen Deadlock verursachen.
2. Die SQL-Statements der betroffenen Sessions herausfinden.
3. In dem `request.log` nachschauen, welche Anfrage an das CAS zu den SQL-Statements passen.
4. Zeiten der gefundenen Aufrufe vergleichen.
   Sind die Zeiten gleich oder sehr nah beieinander,
   hat man die Aufrufe gefunden,
   die das Problem verursachen.
   Man muss dafür sorgen, dass die SQL-Prozeduren der Aufrufe nicht gleichzeitig ausgeführt werden.
   Wenn es nur ein Client ist,
   kann man die betroffenen Anfragen an das CAS in ein `data/x-procedure` packen.
   Andernfalls muss man dafür sorgen, dass die betroffenen Anfragen nicht gleichzeitig an das CAS geschickt werden.
   (Alternativ könnte man es so implementieren, dass man eine Option für das CAS einführt,
   womit sämtliche SQL-Anfragen nacheinander ausgeführt werden.
   Dadurch wären SQL-Deadlocks durch das CAS nicht mehr möglich.)

## setup-Befehl hat einen Fehler.

### 0815-Lösung

Manchmal löst man das Problem indem man eine neue leere Datenbank dafür verwendet,
anstatt eine bereits vorhanden (`create database <name>`).

### `aero.minova.core.application.system.app.setup.xml` nicht gefunden.

Die Fehlermeldung ist:
```
"message": "java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: No setup file found with the name aero.minova.core.application.system.app.setup.xml",
```

Der Fehler ist, dass das veraltete `core.application.system.app` verwendet wird.
Eigentlich müsste diese Abhängigkeit durch `cas.app` ersetzt werden,
was allerdings zeitaufwendig ist (link:https://github.com/minova-afis/aero.minova.cas/issues/296[Ticket]).
Als Hotfix kann die `core.application.system.app`-Version auf `12.42.0` gesetzt werden.
Entweder ist `core.application.system.app` in der betroffenen Version direkt als Abhängigkeit gelistet und
braucht nur aktualisiert zu werden,
oder die Abhängigkeit wird indirekt eingeführt.
In dem zweiten Fall muss folgende Abhängigkeit hinzugefügt werden.
Siehe link:../../app.legacy/README.adoc[hier] für Details

```
<dependency>
    <groupId>aero.minova</groupId>
    <artifactId>core.application.system.app</artifactId>
    <version>12.42.0</version>
    <classifier>app</classifier>
</dependency>
```

## Prozedur, View oder anderes SQL-Objekt fehlt nach Setup.

Die setup-Prozedur bricht nach einem Fehler nicht immer mit einem Fehler ab,
sondern führt das Setup fort und gibt am Ende ein OK zurück (link:https://github.com/minova-afis/aero.minova.cas/issues/285[#285]).
In diesem Fall sollte man die Logs des CAS nach dem Wort `Exception` absuchen.

Läuft das CAS lokal in einem Docker-Container,
kann in der Docker-GUI über einen Klick auf den betroffenen Container das Log angeschaut werden.
Dort ist es auch eine Wortsuche möglich.

## ClassNotFoundException - Jar von Abhängigkeit fehlt.

### Es wurde ein App-Projekt mit flaschen Release eingebunden.

In App-Projekten sind unter `src/main/app/extensions` und `traget/extension`
(wird durch Maven und die POM reinkopiert) zusätzliche Jars für das CAS enthalten.
Bei solchen Projekten gibt es in der Regel ein app und ein server Unterprojekt (manchmal mehr).

Wenn dieser Fehler auftritt, ist beim Bau/Release aus irgendwelchen Gründen die server Jar nicht in die app Jar kopiert worden.
Ein häufiger Fehler ist es, dass bei einen Release nicht alles zusammen released wurde,
sondern nur das App-Projekt veröffentlicht wurde,
wodurch die Extension-Jar  im App-Projekt fehlt.

Bei den Projekt `aero.minova.birt.report` bspw. gibt es eine Server und eine Model-Jar,
welche in einem Release des App-Projektes gefehlt hat:

```
2022-05-11T12:25:43.319 Servlet.service() for servlet [dispatcherServlet] in context with path [/cas] threw exception [Request processing failed; nested exception is aero.minova.cas.api.domain.ProcedureException: java.lang.NoClassDefFoundError: aero/minova/BirtRequestParameter] with root cause
java.lang.NoClassDefFoundError: aero/minova/BirtRequestParameter
at aero.minova.birt.report.BirtReport.createOrReadBirtReport(BirtReport.java:215)
at aero.minova.birt.report.BirtReport.lambda$setup$0(BirtReport.java:79)
at aero.minova.cas.controller.SqlProcedureController.executeProcedure(SqlProcedureController.java:181)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

Die betroffene Abhängigkeit muss aktualisiert werden.

### Altes und neues CAS sind im lib-Verzeichnis gemischt.

Das Project `aero.minova.cas` hies mal `aero.minova.core.application.system`.
Es wurde umbenannt, da das Projekt primär unter CAS bekannt war und
der Name somit irritierend war.
Zudem war die Länge des Namens an einigen Stellen hinderlich.

Falls im lib Ordner jar vom alten und vom neuen CAS vorhanden sind,
zeigt sich dies häufig dadurch, dass die eine Klasse von `aero.minova.cas.*` nicht gefunden wird:

```
Caused by: java.lang.ClassNotFoundException: aero.minova.cas.api.domain.ProcedureException
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 19 common frames omitted
```

Es gibt mehrere Lösungen:

* Das Kundenprojekt ist bereits in Ordnung:
in diesem Fall kann man das Kundenprojekt komplett neu bauen und ausliefern.
* Das Kundenprojekt hat selber gemischte Jars:
in diesem Fall sollte man alle Abhängigkeiten auf den neuesten Stand bringen.
* In der XML des Dienste Wrappers steht noch der alte Pfad:
`<arguments>-cp "lib/*" aero.minova.core.application.system.CoreApplicationSystemApplication</arguments>`:
In diesem Fall muss der Pfad aktualisiert werden:
`<arguments>-cp "lib/*" aero.minova.cas.CoreApplicationSystemApplication</arguments>`

## NoSuchBeanException

### Für RestTemplate

Im cas.api Projekt gibt es bereits eine Konfigurationsklasse für RestTemplates.
Falls in einer Extension ein RestTemplate gebraucht wird, einfach mit `RestTemplate template = new RestTemplate();` initialisieren und *nicht* autowiren!

### Für Gson

Im cas.api Projekt wird ebenfalls die Gson-Klasse initialisiert und mit Serializer und Deserializer versehen.
Wird ein Gson-Objekt in einer Klasse gebraucht, kann dieses durch `ClientRestAPI crapi = new ClientRestAPI(); CASRestAPI Gson gson = CASRestAPI.gson();` geholt werden. 
Auch hier darf das Gson-Objekt *nicht* mit der Annotation `@Autowired` versehen werden.

## Einstellung ist nicht gültig.

Manche Einstellungen werden über die `application.properties` getätigt.
Dabei muss beachtet werden,
dass Backslash (`\`) ein Escape-Symbol ist.
Wenn man also wirklich `\` angibt,
muss `\\` stattdessen angegeben werden.
Das kann besonders bei Passwörtern ärgerlich werden.