= ServiceNotifiers Service

Die ServiceNotifier-Extension bietet eine Möglichkeit, Dienste beim CAS zu registrieren.
Sie bietet den Vorteil, dass auf Veränderungen bzw. Updates auf Tabellen gehorcht werden kann und dementsprechende Dienste benachrichtigt werden können.

[plantuml, format="svg", title="title"]
.Caption
....
@startuml
start
:Anfrage;
:SQL-Procedure-Controller;
if (Ist Erweiterung vorhanden?) then (ja)
:Erweiterung ausführen.;
else (nein)
:SQL-Prozedur ausführen.;
endif
if (Ist ServiceNotifier vorhanden?) then (ja)
:Betroffene Dienste informieren.;
endif
:Result auf Anfrage ausgeben.;
stop
@enduml
....

WARNING: Die ServiceNotifiers werden nach den Extensions ausgeführt, da Extensions ebenfalls Veränderungen auf Tabellen auslösen können.

==== ServiceNotifier API

Die zwei wichtigsten Objekte sind die beiden Maps, welche die Informationen zum Dienst und den Prozeduren enthalten:

* *servicenotifier*: Enthält Tupel aus Prozedurenamen und Tabellennamen.
* *newsfeeds*: Enthält Tupel aus Dienstnamen und Tabellennamen.

Folgende Extensions können mithilfe von *data/procedure* aufgerufen werden:

* registerService: Registriert einen Dienst mit den übergebenen Parametern in der xtcasCASServices Tabelle.
* unregisterService: Meldet den Dienst mit den übergebenen Parametern ab und löscht ihn aus der xtcasCASServices Tabelle.
* registerProcedureNewsfeed: Verknüpft die übergebenen Prozedurnamen mit den übergebenen Topics. Die Verbindung zeigt, welche Prozeduren Änderungen auf bestimmten Tabellen auslösen. Die Informationen werden in der xtcasProcedureNewsfeed gespeichert.
* unregisterProcedureNewsfeed: Löscht eine Verknüpfung von Prozedur und Tabelle aus der Tabelle xtcasProcedureNewsfeed.
* unregisterProcedureNewsfeedCompletely: Löscht alle Verknüpfungen zwichen einer Prozedur und den dazugehörigen Tabellen.
* registerNewsfeedListener: Speichert, welche Dienste auf welche Topics horchen. Der Dienstname und der Tabellenname müssen als Values übergeben werden. Die Informationen werden in der xtcasNewsfeedListener gespeichert.
* unregisterNewsfeedListener: Löscht den Vermerk des Dienstes auf das Topic wieder aus der Tabelle xtcasNewsfeedListener.
