name: Continous Integration
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  Build: #Change the branch to which is pointint due to issues with sonarqube step. (After issue is resolved please move back)
    uses: minova-afis/aero.minova.os.github.workflows/.github/workflows/java-continuous-integration.yml@hoj_java_21
    secrets: inherit
    with:
      dependency-check-goal: 'help'
