name: Release Test
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        default: 'warning'
      nextDevelopmentVersion:
        description: 'Next Development Version ("-SNAPSHOT" muss nicht angegeben werden.)'
        required: true
        default: 'warning'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build
        run: |
          git config --global user.email "service@minova.com"
          git config --global user.name "minova-worker"
          cd $GITHUB_WORKSPACE
          mvn --batch-mode release:prepare release:perform -P repo-github \
            -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
            -DdevelopmentVersion=${{ github.event.inputs.nextDevelopmentVersion }}-SNAPSHOT \
            --settings .github/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MINOVA_GITHUB_MAVEN_DEPENDENCIES_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MINOVA_GITHUB_MAVEN_DEPENDENCIES_TOKEN }}
          GITHUB_RELEASE_USERNAME: minova-worker
          GITHUB_RELEASE_TOKEN: ${{ secrets.MINOVA_GITHUB_RELEASE_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.MINOVA_GITHUB_RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}